name: Publish os-api-linux-hosts-db to npmjs
on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/linux-hosts-db.yml"
      - "linux-hosts-db/**"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/linux-hosts-db.yml"
      - "linux-hosts-db/**"

env:
  # Setting an environment variable with the value of a configuration variable
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  PACKAGE_NAME: "unknown"
  PACKAGE_VERSION: "unknown"
  NPM: "npm"
  NPM_VERSION: "unknown"
  HAVE_COVERAGE_SCRIPT: false
  HAVE_VALIDATE_SCRIPT: false
  HAVE_LINT_SCRIPT: false
  HAVE_UNIT_TEST_SCRIPT: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./linux-hosts-db
    steps:
      - uses: dcarbone/install-jq-action@v2
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y libnss-db

      - name: Get Npm Package Env Variables
        run: bash ../bin/package-envs.sh >> $GITHUB_ENV

      - uses: pnpm/action-setup@v4
        if: env.NPM == 'pnpm'
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Get current npmjs version for ${{env.PACKAGE_NAME}}
        run: |
          echo "NPM_VERSION=$(curl -s https://registry.npmjs.org/${{ env.PACKAGE_NAME }} | jq -r '."dist-tags".latest')" >> $GITHUB_ENV

      - name: Install dependencies
        run: ${{ env.NPM }} install

      - name: Run validate
        if: env.HAVE_VALIDATE_SCRIPT == 'true'
        run: ${{ env.NPM }} run validate

      - name: Run unit tests
        if: env.HAVE_UNIT_TEST_SCRIPT == 'true'
        run: ${{ env.NPM }} test

      - name: Run linter checks
        if: env.HAVE_LINT_SCRIPT == 'true'
        run: ${{ env.NPM }} run lint

      - name: Run and publish code coverage
        if: |
          github.ref == 'refs/heads/main' &&
          env.CC_TEST_REPORTER_ID != '' &&
          env.HAVE_COVERAGE_SCRIPT == 'true'
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ env.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: ${{ env.NPM }} run coverage

      # npm publish when PR done
      - name: Publish ${{env.PACKAGE_NAME}} ${{env.PACKAGE_VERSION}}
        run: ${{ env.NPM }} publish --no-git-checks --access public
        if: |
          github.ref == 'refs/heads/main' &&
          env.NPM_TOKEN != '' &&
          env.PACKAGE_VERSION != env.NPM_VERSION
        env:
          NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}
